### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by AdrianVollmer** [AdrianVollmer/PowerHub#14]

**Comment by mars-online** [comment]
Try one of these

![hub-128](https://user-images.githubusercontent.com/41105217/59918309-a933f980-9424-11e9-9bbd-f6e45c218fd5.png)
![hub-96](https://user-images.githubusercontent.com/41105217/59918310-a933f980-9424-11e9-874f-d52322386657.png)
![hub-32](https://user-images.githubusercontent.com/41105217/59918311-a933f980-9424-11e9-95a8-7263ee907cb3.png)
![hub-16](https://user-images.githubusercontent.com/41105217/59918312-a933f980-9424-11e9-90d9-7572a39aaa1a.png)

[hub.xcf.zip](https://github.com/AdrianVollmer/PowerHub/files/3314160/hub.xcf.zip)

**Comment by patrickhener** [comment]
If you do not opt for a picture type Icon you might as well use https://favicon.io/ to generate one spelling "PH" in some way.
