### ISSUE TITLE
Uri path

### ISSUE THREAD

**Issue by userdol** [AdrianVollmer/PowerHub#3]
powerhub.py: error: the following arguments are required: URI_HOST 
What to indicate here? IP? Ip my server?

**Comment by T3KX** [comment]
I had this problem too , i pass my ip at the end line so, with no switch in front

python3.7 powerhub.py -p 1234 -l 0.0.0.0 -n -u 1235 --uri-path /tmp --no-auth 192.168.0.16

from arg.py
parser.add_argument(
    '-n', '--noisy', default=True, dest="NOISY",
    action="store_false",
    help="allow noisy actions like loading mimikatz"
)

parser.add_argument(
    dest="URI_HOST", type=str,
    help="the hostname where the target can reach the server"
)

parser.add_argument(
    '-u', '--uri-port', dest="URI_PORT", type=int,
    default=0,
    help="the port where the target can reach the server (default: LPORT)"

**Comment by AdrianVollmer** [comment]
This is explained in the readme and the online help. You need to pass the host where the target can reach you. In most cases, this is your IP address.
