### ISSUE TITLE
1.3 fails to show installed modules

### ISSUE THREAD

**Issue by ozozial** [AdrianVollmer/PowerHub#39]
Been in love with this tool and its honestly a masterpiece.

One issue with the new version 1.3 ...
When I updated from 1.2 to 1.3 I lost the ability to view my installed modules.

![Screenshot_2019-08-02-16-30-52~2](https://user-images.githubusercontent.com/51517349/62398599-2f288180-b547-11e9-986c-d939ea989f19.png)

I have remedied this by staying at 1.2 but would like to hop on 1.3 due to the TLS jawn.

**Comment by AdrianVollmer** [comment]
Thank you for your kind words!

So in 1.3 I changed the location of the modules. The directory has previously been located in the root directory of this repository. It's now in `$XDG_DATA_HOME/powerhub`, or `~/.local/share/powerhub` by default. You can simple move your module directory there. Hope that helps.

I documented this change in the changelog, but I understand that I could have been clearer about this breaking change.

**Comment by AdrianVollmer** [comment]
I assume you figured it out
