### ISSUE TITLE
Vulnerability disclosure?

### ISSUE THREAD

**Issue by six-two** [AdrianVollmer/PowerHub#54]
Hi AdrianVollmer,

I believe I may have found some potential vulnerabilities in PowerHub. Is there a way to privately disclose them to you, or should I open an (public) issue here?

BR
six-two

**Comment by AdrianVollmer** [comment]
DM me on Twitter (@mr_mitm) or send me an e-mail (adrian.vollmer @ syss.de) [pgp key](https://www.syss.de/fileadmin/dokumente/PGPKeys/Adrian_Vollmer.asc)

**Comment by AdrianVollmer** [comment]
I received and decrypted your message, thanks. I'll take a look and get back to you.

**Comment by AdrianVollmer** [comment]
See mail
