### ISSUE TITLE
Failed to load in target system : unable to connect to server

### ISSUE THREAD

**Issue by 7h3w4lk3r** [AdrianVollmer/PowerHub#56]
i tried with both the pip packages and github installation. the server is up and the client can connect and GET some of the scripts but after a few seconds troughs an error.

![image](https://user-images.githubusercontent.com/61451071/191094671-d68511b4-4efc-4785-9801-063add263676.png)

**Comment by AdrianVollmer** [comment]
Looks like you set `127.0.0.1` as your URI host. Unless you are then running the powershell command on the same machine, this can't work. You must set it to an IP address or hostname that is reachable by the system on which the powershell command runs.

**Comment by 7h3w4lk3r** [comment]
sorry, my bad. i thought the `uri host` parameter is for flask service.
