### ISSUE TITLE
Defender Trojan:Win32/AmsiTamper.A!ams

### ISSUE THREAD

**Issue by T3KX** [AdrianVollmer/PowerHub#7]
Not sure if i am missing something, But i get flag by defender as Trojan:Win32/AmsiTamper.A!ams

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763

Defender 1.289.1512.0

**Comment by AdrianVollmer** [comment]
Damn... Defender never caught it on my system.

can you try again with the latest commit please? That's my last idea for now

**Comment by T3KX** [comment]
Adrian,

Yep , latest commit fix it, awesome work , i think it will come handy.
love the work on rdp too btw.

Thanks

**Comment by AdrianVollmer** [comment]
great! thanks a lot for testing
